# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your actual API key

# OpenAI API Key (replace with your actual key)
OPENAI_API_KEY = "your-api-key-here"

# Optional: Add other API keys if needed
# ANTHROPIC_API_KEY = "your-anthropic-key-here"
# GOOGLE_API_KEY = "your-google-key-here"

# Vector store configuration
VECTOR_STORE_ID = "vs_689b5d0712108191a132efe2deff75f4"
